### ISSUE TITLE
Unable to mount /etc/apcupsd/ as a volume

### ISSUE THREAD

**Issue by AndreaPro** [gregewing/apcupsd#1]
Hello, I wanted to mount /etc/apcupsd as a volume.
This is the docker-compose that I am using:
```
services:
  apcupsd:
    container_name: apcupsd
    devices:
    - /dev/bus/usb/001/006
    environment:
      TZ: Europe/Rome
    image: gregewing/apcupsd:latest
    ports:
    - published: 3551
      target: 3551
    privileged: true
    volumes:
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw
    - /apps/apcupsd/config:/etc/apcupsd:rw
version: '3.3'
```
This is the error that I see if I run docker-compose logs -f
```
Attaching to apcupsd
apcupsd    | 0.005 apcupsd: drivers.c:182 Warning: no UPS driver found (ups->mode.type=0).
apcupsd    | apcupsd FATAL ERROR in apcupsd.c at line 196
apcupsd    | Apcupsd cannot continue without a valid driver.
apcupsd exited with code 1
```
If I remove     `- /apps/apcupsd/config:/etc/apcupsd:rw` from the compose file I have a working container without errors but I have to reconfigure it every time and is not very pratical to use it in this way
