### ISSUE TITLE
Volumes need to be defined in docker-compose

### ISSUE THREAD

**Issue by bnhf** [gregewing/apcupsd#5]
@gregewing 

Rather than tacking-on to the PR that didn't make the grade, I thought I'd open an issue to expand on a couple of topics:

Following the direction you want to go, and for the purposes of the README with the recently updated docker-compose, the volume needs to be defined in the yaml. It does not need to be created in advance. Also, the name of the stack is appended to the front of the volume, so a volume name of "config" results in a directory named "apcupsd_config" in /var/lib/docker/volumes (assuming a stack name of apcupsd) :

```yml
version: '3.7'
services:
  apcupsd:
    image: gregewing/apcupsd:latest
    container_name: apcupsd
    devices:
      - /dev/usb/hiddev0 # This device needs to match what the APC UPS on your system uses.
    ports:
      - 3551:3551
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - config:/etc/apcupsd
    restart: unless-stopped
volumes:
  config:
```
And this results in the following directory being created, and populated:

![screenshot-raspberrypi10-2023 02 02-19_05_34](https://user-images.githubusercontent.com/41088895/216495252-752d7f8f-3456-49c4-b3f8-66815abd05c3.png)

I think you'll find that the start.sh in the PR works equally well whether the binding is to a directory (like /data/apcupsd) or to a volume (like config:). Either way, somebody can launch an apcupsd daemon container all from a Portainer-Stack, without having to execute or modify anything from the command line.

If you're willing, I'd like to figure out why you were unsuccessful using the docker-compose from my fork. I've been using it for my "Ultimate APC UPS Monitoring" project, and it's been dead-simple and reliable so far. Did your portainer stack look like this?:

![screencapture-raspberrypi10-9000-2023-01-30-14_29_02](https://user-images.githubusercontent.com/41088895/216494825-cdd853cd-8140-4462-b41a-49ff4840fdf8.png)

**Comment by gregewing** [comment]
Well, admittedly I don't use Docker Compose, and I tested your fork by creating a container manually and exposing to it the various resources and a blank volume.  Yes, the volume gets populated, but if I remove and recreate the container any customizations that I have made in them are over-written, which is far from ideal for wen a new release of the container becomes available and watchtower does its thing.  Is suspect this is a result of your start.sh script.

We should not be prescriptive about how a container is created, so it should work the same way regardless of how the container is created or managed (docker run / portainer / docker compose / etc.)

I'll work on the job of using Docker Environment variables to push configs to the apcupsd.config file, but I'm busy with other projects and starting a new job too.  I know how to do it in a way that will be non-destructive and have it persist a recreation of the container while re-using an existing mounted folder or volume.

**Comment by bnhf** [comment]
@gregewing 

I spent a few minutes this morning looking at this, and it turns out that I hadn't rebuilt the image on Docker Hub with the changes I submitted in the PR. The start.sh in the Docker Hub container was an earlier version, where I was moving the files unconditionally. Anyway, the version in the PR was correct (with the addition of conditional moves for hosts.conf and doshutdown as referenced  in the PR comment).

I've rebuilt the multi-arch container on Docker Hub now, as I know you'll want to do some additional testing. I've tested it using   a docker volume, where on the first run I set the UPSNAME environment variable -- then stopped the stack and removed the environment variable. apcupsd.conf was not overwritten on the next run, evidenced by the UPSNAME setting in the file remaining in its previously modified state.

Apologies for not updating my Docker Hub container with the latest script -- the fact that apcupsd.conf was getting overwritten on each container run, wasn't obvious on my end since my desired changes (via the environment variables) were also getting performed on each run.

**Comment by bnhf** [comment]
@gregewing 

Me again. :-) OK, so I've officially tested every bind mount scenario I could think of, and they're all working with bnhf/apcupsd:latest. There are differences in the docker-compose (just as there are from the command line) depending on which approach you use, directory binding, new volume binding or existing volume binding. These differences only come into play when there are no existing config files -- after the files are created, they will persist and be used, unless specifically deleted.

Here's the "universal" docker-compose with comments regarding first-run options:

```yml
version: '3.7'
services:
  apcupsd:
    image: bnhf/apcupsd:latest
    container_name: apcupsd
    devices:
      - /dev/usb/hiddev0 # Check the /dev/usb folder on the UPS connected system to determine your options here
    ports:
      - 3551:3551
    environment:
      - UPSNAME=${UPSNAME} # This name will be used in a number of monitoring applications. 1 to 8 characters, no spaces
      - UPSCABLE=${UPSCABLE} # Default is usb
      - UPSTYPE=${UPSTYPE} # Default is usb
      - TZ=${TZ} # Local timezone of the UPS device
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /data/apcupsd:/etc/apcupsd # /etc/apcupsd can be bound to a directory or a docker volume
    restart: unless-stopped
# volumes: # Use this section for volume bindings only.
#   config: # The name of the stack will be appended to the beginning of this volume name, if the volume doesn't already exist
#           # If you created the docker volume in advance, use that name here, and for the /etc/apcupsd binding above
#     external: true # Use this directive if you created the docker volume in advance
```

Also, I added some basic log output to indicate whether existing files are being used, and if apcupsd.conf variables are being mofified:

![screenshot-raspberrypi10-2023 02 03-20_38_29](https://user-images.githubusercontent.com/41088895/216746127-08c1c815-9711-491e-b398-476fb2a948be.png)
