### ISSUE TITLE
Environment variables and sample docker-compose for master-slave setups

### ISSUE THREAD

**Issue by bnhf** [gregewing/apcupsd#6]
@gregewing 

Hey Greg - I know you've got a lot going on at the moment, but hopefully in the great spirit of open source we can enhance this project concurrently.

If you haven't seen, I added some additional comments to the open "Volumes" issue regarding the bnhf/apcupsd:latest container not being up-to-date with the PR I submitted. I've rectified that, and tested bind mounts of all types, and I think we're in good shape there. Now that I'm focusing on the master-slave shutdown capability of apcupsd, I see that we need all of the scripts and config files present in /etc/apcupsd, and that's been handled in this update.

What I'm working on now, which I hope you'll like, are additional environment variables to support setting up the UPS-connected computer as a master and any number of other boxes as slaves. For those who like the command line and editing config files nothing will change, but for those who prefer tools like Portainer the whole thing can be done from a stack.

This isn't quite ready to test yet, but I wanted to give you a preview of what I have in mind. Here are the paired down docker-compose yaml examples for a master-slave setup, followed by a "universal" fully annotated version that can be used for either master or slave:

Master with minimum required settings using a directory bind mount:

```yml
version: '3.7'
services:
  apcupsd:
    image: bnhf/apcupsd:test
    container_name: apcupsd
    devices:
      - /dev/usb/hiddev0
    ports:
      - 3551:3551
    environment:
      - UPSNAME=${UPSNAME}
      - APCUPSD_SLAVES=${APCUPSD_SLAVES} # Enter the APUPSD_SLAVES IP list here (space separated)
      - TZ=${TZ}
   volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /data/apcupsd:/etc/apcupsd
     restart: unless-stopped
```

Slaves with minimum required settings using a directory bind mount:

```yml
version: '3.7'
services:
  apcupsd:
    image: bnhf/apcupsd:test
    container_name: apcupsd
    ports:
      - 3551:3551
    environment:
      - UPSCABLE=${UPSCABLE} # On APCUPSD_SLAVES set the value to ether
      - UPSTYPE=${UPSTYPE} # On APCUPSD_SLAVES set the value to net
      - DEVICE=${DEVICE} # On APCUPSD_SLAVES set the IP address of the APCUPSD_MASTER with the listening port (:3551)
      - TZ=${TZ}
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /data/apcupsd:/etc/apcupsd
    restart: unless-stopped
```

And finally, here's the fully annotated "universal" docker-compose with all of the variables I've identified thus far, that someone may want to tweak:

```yml
version: '3.7'
services:
  apcupsd:
    image: bnhf/apcupsd:test
    container_name: apcupsd
    devices:
      - /dev/usb/hiddev0 # This device needs to match what the APC UPS on your APCUPSD_MASTER system uses -- Comment out this section on APCUPSD_SLAVES
    ports:
      - 3551:3551
    environment:
      - UPSNAME=${UPSNAME} # Sets a name for the UPS (1 to 8 chars), that will be used by System Tray notifications, apcupsd-cgi and Grafana dashboards
#      - UPSCABLE=${UPSCABLE} # Usually doesn't need to be changed on system connected to UPS. (default=usb) On APCUPSD_SLAVES set the value to ether
#      - UPSTYPE=${UPSTYPE} # Usually doesn't need to be changed on system connected to UPS. (default=usb) On APCUPSD_SLAVES set the value to net
#      - DEVICE=${DEVICE} # Use this only on APCUPSD_SLAVES to set the hostname or IP address of the APCUPSD_MASTER with the listening port (:3551)
#      - POLLTIME=${POLLTIME} # Interval (in seconds) at which apcupsd polls the UPS for status (default=60)
#      - ONBATTERYDELAY=${ONBATTERYDELAY} # Sets the time in seconds from when a power failure is detected until an onbattery event is initiated (default=6)
#      - BATTERYLEVEL=${BATTERYLEVEL} # Sets the daemon to send the poweroff signal when the UPS reports a battery level of x% or less (default=5)
#      - MINUTES=${MINUTES} # Sets the daemon to send the poweroff signal when the UPS has x minutes or less remaining power (default=5)
#      - TIMEOUT=${TIMEOUT} # Sets the daemon to send the poweroff signal when the UPS has been ON battery power for x seconds (default=0)
#      - SELFTEST=${SELFTEST} # Sets the daemon to ask the UPS to perform a self test every x hours (default=336)
#      - APCUPSD_SLAVES=${APCUPSD_SLAVES} # If this is the APCUPSD_MASTER, then enter the APUPSD_SLAVES list here (space separated)
      - TZ=${TZ}
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket # Required to support host shutdown from the container
      - /data/apcupsd:/etc/apcupsd # /etc/apcupsd can be bound to a directory or a docker volume
    restart: unless-stopped
# volumes: # Use this section for volume bindings only
#   config: # The name of the stack will be appended to the beginning of this volume name, if the volume doesn't already exist
#     external: true # Use this directive if you created the docker volume in advance
```
I have pretty much all of this working already with the exception of the APCUPSD_SLAVES variable, but the code for that is already present in some work I did on a apcupsd-cgi container -- so I just need to port it over.

Let me know what you think when you have a spare a moment. If you're open to some further collaboration, I think we can add some nice features to this project with a minimum of your bandwidth. Cheers.
